### ISSUE TITLE
4. Upload Image

### ISSUE THREAD

**Issue by hczirjek** [raduf24/VisualMoodTracker#4]
It allows us to select an image, in any possible format, from a device and upload it to our application to be processed.
After clicking a button it opens a file picker to search and select the picture you want to upload.

**Comment by BarabasiB** [comment]
Limits of the API:
- The supported input image formats includes JPEG, PNG, GIF(the first frame), BMP.
- Image file size should be no larger than 4MB
- The detectable face size range is 36x36 to 4096x4096 pixels. Faces out of this range will not be detected
- Some faces may not be detected due to technical challenges, e.g. very large face angles (head-pose), large occlusion. Frontal and near-frontal faces have the best results
